# Generated by Django 4.1.3 on 2022-12-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catagory',
            table='catagory',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='Equipment',
        ),
    ]
