# Generated by Django 4.1.3 on 2022-12-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expect_return_date', models.DateTimeField(blank=True)),
                ('reason', models.TextField(blank=True, max_length=1000, null=True)),
                ('date_return', models.DateTimeField(blank=True, null=True)),
                ('approval', models.IntegerField(default=0)),
            ],
        ),
    ]
