# Generated by Django 4.1.3 on 2022-12-06 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0001_initial'),
        ('Equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approval_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipment.equipment'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
