# Generated by Django 4.1.3 on 2022-12-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
    ]
