# Generated by Django 4.1.3 on 2022-12-22 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0003_alter_request_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approval_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Admin_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
